// <auto-generated />
namespace Tuatara.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _20170214_v2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20170214_v2));
        
        string IMigrationMetadata.Id
        {
            get { return "201702141818402_20170214_v2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
